SELECT CATEGORY
      ,MAX(PRICE)
      ,PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE CATEGORY IN ('과자','국','김치','식용유')
AND PRICE IN (SELECT MAX(PRICE)
              FROM FOOD_PRODUCT
              WHERE CATEGORY = A.CATEGORY)
GROUP BY CATEGORY,PRODUCT_NAME
ORDER BY MAX(PRICE) DESC