SELECT BO.TITLE, BO.BOARD_ID, RE.REPLY_ID, RE.WRITER_ID, RE.CONTENTS, TO_CHAR(RE.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD BO, USED_GOODS_REPLY RE
WHERE BO.BOARD_ID = RE.BOARD_ID
AND BO.CREATED_DATE 
BETWEEN TO_DATE('2022-10-01 00:00:00','YYYY-MM-DD HH24:MI:SS') 
AND TO_DATE('2022-10-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY RE.CREATED_DATE,BO.TITLE