-- 희귀도가 'RARE'인 아이템
-- ITEM_ID, ITEM_NAME, RARITY 출력
-- ITEM_ID DESC

SELECT C.ITEM_ID
     , C.ITEM_NAME
     , C.RARITY
  FROM ITEM_INFO A
  LEFT
  JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
  JOIN ITEM_INFO C
    ON B.ITEM_ID = C.ITEM_ID
   AND A.RARITY  = 'RARE'
  ORDER BY C.ITEM_ID DESC